project:
  type: website

website:
  title: "Jorick van der Hoeven"
  open-graph: true
  navbar:
    left:
      - text: Portfolio
        file: portfolio.qmd
    right:
      - icon: github
        href: https://github.com/JorickvdHoeven
format:
  html:
    theme:
      dark: cyborg
      light: cyborg
    css: styles.css

execute:
  freeze: auto


